version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./src:/var/www
    ports:
      - "5200:5200"
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    ports:
      - "80:80"
    networks:
      - app-network
  vite:
    image: node:16-alpine
    restart: unless-stopped
    volumes:
      - ./src:/var/www
    ports:
      - "3000:3000"
    networks:
      - app-network
    command: sh -c "cd /var/www && npm run dev"
  db:
    image: percona:latest
    restart: unless-stopped
    volumes:
      - ./docker/config/mysql/my.cnf:/etc/mysql/my.cnf
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "db"
      MYSQL_DATABASE: "cube"
      MYSQL_USER: "db"
      MYSQL_PASSWORD: "db"
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
    driver: bridge
