#!/usr/bin/env bash

role=${CONTAINER_ROLE:-app}
env=${APP_ENV:-production}

if [ "$env" = "local" ]; then
    cd /var/www && php artisan config:cache && php artisan route:cache && php artisan view:cache
fi

# @TODO start horizon

if [ "$role" = "app" ]; then
    echo "Starting app..."
    exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
fi

if [ "$role" = "vite" && "$env" = "develop" ]; then
    echo "Starting vite..."
    cd /var/www && npm run dev
fi
